SYS_AUTOSTART:    4001

MC_YAWRATE_P:     0.2
MC_YAWRATE_I:     0.1
MC_YAWRATE_MAX:   200.0

# For Cyphal
UCAN1_ESC_FUNC1:  101
UCAN1_ESC_FUNC2:  102
UCAN1_ESC_FUNC3:  103
UCAN1_ESC_FUNC4:  104

# For DroneCAN
UAVCAN_EC_FUNC1:  101
UAVCAN_EC_FUNC2:  102
UAVCAN_EC_FUNC3:  103
UAVCAN_EC_FUNC4:  104
