UCAN1_ESC_FUNC1:  101
UCAN1_ESC_FUNC2:  102
UCAN1_ESC_FUNC3:  103
UCAN1_ESC_FUNC4:  104
UCAN1_ESC_FUNC5:  0
UCAN1_ESC_FUNC6:  0
UCAN1_ESC_FUNC7:  0
UCAN1_ESC_FUNC8:  0
UCAN1_ESC_FUNC9:  0

# UCAN1_FB4_SUB:    -1
# UCAN1_FB5_SUB:    -1
# UCAN1_FB6_SUB:    -1
# UCAN1_FB7_SUB:    -1
