# 1. Simulator parameters
use_sim_time: true
use_rungekutta4integrator : false

# 2. Drone position and initial state:
# inno:
lat_ref : 55.7544426
lon_ref : 48.742684
alt_ref : -6.5
# or as in gazebo:
# lat_ref : 47.3977420
# lon_ref : 8.5455940
# alt_ref : 488.157
init_pose: [0.00, 0.00, 0.0,
            0.00, 0.00, +0.00, +1.00]  # roll, pitch, yaw, weight

# 3. vehicle settings
vehicle_mass :              1.5       # kg
motor_time_constant:        0.02      # sec
motor_rotational_inertia:   6.62e-6   # kg m^2
moment_arm:                 0.08      # m ???
thrust_coefficient:         1.91e-6   # N/(rad/s)^2"
torque_coefficient:         2.6e-7    # Nm/(rad/s)^2
drag_coefficient:           0.1       # N/(m/s)
max_prop_speed :            2200      # rad/s

# 4. Imu noise
accelerometer_variance:     0.0001    # 0.001
gyroscope_variance:         0.00001   # 0.001
accelerometer_biasinitvar:  0.00001   # 0.005
gyroscope_biasinitvar:      0.00001   # 0.003
accelerometer_biasprocess:  0.0       # 1.0e-7
gyroscope_biasprocess:      0.0       # 1.0e-7