mass:                   7.0         # kg
gravity:                9.80665     # n/sec^2
atmoRho:                1.2         # air density (kg/m^3)
wingArea:               0.37        # m^2
characteristicLength:   1.50        # m

inertia:                [0.62684, 0,      0,
                         0,       0.6444, 0,
                         0,       0,      1.26242]  # kg*m^2

propellersLocationX:    0.445       # m
propellersLocationY:    0.422       # m
propellersLocationZ:    -0.031      # m

# double massUncertainty;                         // mass multiplier
# double inertiaUncertainty;                      // mass multiplier

actuatorMin:            [0,     0,    0,    0,    0,    -20, -20, -20]
actuatorMax:            [1000,  1000, 1000, 1000, 1000, 20,  20,  20]

accVariance:            0.005
gyroVariance:           0.005

