CA_ROTOR_COUNT:   9     # Total number of motors

CA_ROTOR0_AX:     0.0
CA_ROTOR0_AY:     0.0
CA_ROTOR0_AZ:     -1.0
CA_ROTOR0_KM:     0.05
CA_ROTOR0_PX:     1.0
CA_ROTOR0_PY:     1.0
CA_ROTOR0_PZ:     0.0

CA_ROTOR1_AX:     0.0
CA_ROTOR1_AY:     0.0
CA_ROTOR1_AZ:     -1.0
CA_ROTOR1_KM:     0.05
CA_ROTOR1_PX:     -1.0
CA_ROTOR1_PY:     -1.0
CA_ROTOR1_PZ:     0.0

CA_ROTOR2_AX:     0.0
CA_ROTOR2_AY:     0.0
CA_ROTOR2_AZ:     -1.0
CA_ROTOR2_KM:     -0.05
CA_ROTOR2_PX:     1.0
CA_ROTOR2_PY:     -1.0
CA_ROTOR2_PZ:     0.0

CA_ROTOR3_AX:     0.0
CA_ROTOR3_AY:     0.0
CA_ROTOR3_AZ:     -1.0
CA_ROTOR3_KM:     -0.05
CA_ROTOR3_PX:     -1.0
CA_ROTOR3_PY:     1.0
CA_ROTOR3_PZ:     0.0

CA_ROTOR4_AX:     0.0
CA_ROTOR4_AY:     0.0
CA_ROTOR4_AZ:     -1.0
CA_ROTOR4_KM:     0.05
CA_ROTOR4_PX:     1.0
CA_ROTOR4_PY:     1.0
CA_ROTOR4_PZ:     0.0

CA_ROTOR5_AX:     0.0
CA_ROTOR5_AY:     0.0
CA_ROTOR5_AZ:     -1.0
CA_ROTOR5_KM:     0.05
CA_ROTOR5_PX:     -1.0
CA_ROTOR5_PY:     -1.0
CA_ROTOR5_PZ:     0.0

CA_ROTOR6_AX:     0.0
CA_ROTOR6_AY:     0.0
CA_ROTOR6_AZ:     -1.0
CA_ROTOR6_KM:     -0.05
CA_ROTOR6_PX:     1.0
CA_ROTOR6_PY:     -1.0
CA_ROTOR6_PZ:     0.0

CA_ROTOR7_AX:     0.0
CA_ROTOR7_AY:     0.0
CA_ROTOR7_AZ:     -1.0
CA_ROTOR7_KM:     -0.05
CA_ROTOR7_PX:     -1.0
CA_ROTOR7_PY:     1.0
CA_ROTOR7_PZ:     0.0

CA_ROTOR8_AX:     1.0
CA_ROTOR8_AY:     0.0
CA_ROTOR8_AZ:     0.0
CA_ROTOR8_KM:     0.05
CA_ROTOR8_PX:     0.0
CA_ROTOR8_PY:     0.0
CA_ROTOR8_PZ:     0.0
