UCAN1_ESC_FUNC1:  101 # motor 1
UCAN1_ESC_FUNC2:  102 # motor 2
UCAN1_ESC_FUNC3:  103 # motor 3
UCAN1_ESC_FUNC4:  104 # motor 4
UCAN1_ESC_FUNC5:  105 # motor 5
UCAN1_ESC_FUNC6:  106 # motor 6
UCAN1_ESC_FUNC7:  107 # motor 7
UCAN1_ESC_FUNC8:  108 # motor 8
UCAN1_ESC_FUNC9:  109 # motor 9
UCAN1_ESC_FUNC10: 201 # servo 1 (left aileron)
UCAN1_ESC_FUNC11: 202 # servo 2 (right aileron)
UCAN1_ESC_FUNC12: 203 # servo 3 (elevators)
UCAN1_ESC_FUNC13: 204 # servo 4 (rudders)

UCAN1_FB4_SUB:    2504
UCAN1_FB5_SUB:    2505
UCAN1_FB6_SUB:    2506
UCAN1_FB7_SUB:    2507
