# 1. Common
CYPHAL_ENABLE:    1

# 2. Cyphal registers
UCAN1_ACCEL_SUB:  2400
UCAN1_GYRO_SUB:   2401
UCAN1_BAROP0_SUB: 2404
UCAN1_GPS0_SUB:   2406
UCAN1_GPSSA0_SUB: 2407
UCAN1_GPSST0_SUB: 2408
UCAN1_GPSPD0_SUB: 2409
UCAN1_MAG0_SUB:   2402
UCAN1_ESC_PUB:    2342

# 3. Sensor calibration
# 3.1. Gyro
CAL_GYRO0_ID:     8781824
CAL_GYRO0_PRIO:   75
CAL_GYRO0_ROT:    0
CAL_GYRO0_XOFF:   0.000040318540413864
CAL_GYRO0_YOFF:   -0.000227847383939661
CAL_GYRO0_ZOFF:   0.000082234357250854

# 3.2. Accelerometer
CAL_ACC0_ID:      8388608
CAL_ACC0_PRIO:    75
CAL_ACC0_ROT:     0

# 3.3. Magnetometer
CAL_MAG0_ID:      8912896
CAL_MAG0_PRIO:    75
CAL_MAG0_ROT:     0

# 4. PID regulator
# ...
