SYS_AUTOSTART:    13000
SYS_CTRL_ALLOC:   1

UAVCAN_EC_FUNC1:  101
UAVCAN_EC_FUNC2:  102
UAVCAN_EC_FUNC3:  103
UAVCAN_EC_FUNC4:  104
UAVCAN_EC_FUNC5:  105

UAVCAN_SV_FUNC1:  201
UAVCAN_SV_FUNC2:  202
UAVCAN_SV_FUNC3:  203
UAVCAN_SV_FUNC4:  204
