SYS_AUTOSTART:    12001

UCAN1_ESC_FUNC1:  101
UCAN1_ESC_FUNC2:  102
UCAN1_ESC_FUNC3:  103
UCAN1_ESC_FUNC4:  104
UCAN1_ESC_FUNC5:  105
UCAN1_ESC_FUNC6:  106
UCAN1_ESC_FUNC7:  107
UCAN1_ESC_FUNC8:  108

MC_YAWRATE_P:     0.2
MC_YAWRATE_I:     0.1
MC_YAWRATE_MAX:   200.0
