# 1. Common
CYPHAL_ENABLE:    1

# 2. Cyphal registers
UCAN1_ESC_PUB:    2342
UCAN1_READ_PUB:   2343

UCAN1_IMU_SUB:    2300
# UCAN1_ACCEL_SUB:  2400
# UCAN1_GYRO_SUB:   2401

UCAN1_MAG0_SUB:   2402

UCAN1_BAROT0_SUB: 2403
UCAN1_BAROP0_SUB: 2404

UCAN1_GPS0_SUB:   2005

UCAN1_DPRES0_SUB: 2600
UCAN1_DPRES1_SUB: 2601

UCAN1_FB0_SUB:    2500
UCAN1_FB1_SUB:    2501
UCAN1_FB2_SUB:    2502
UCAN1_FB3_SUB:    2503

UCAN1_BMS_ES_SUB: 2700  # BMS energy_source
UCAN1_BMS_BS_SUB: 2701  # BMS battery_status
UCAN1_BMS_BP_SUB: 2702  # BMS battery_parameters

# 3. Sensor calibration
# 3.1. Gyro
CAL_GYRO0_ID:     8781824
CAL_GYRO0_PRIO:   50
CAL_GYRO0_ROT:    0
CAL_GYRO0_XOFF:   0.000040318540413864
CAL_GYRO0_YOFF:   -0.000227847383939661
CAL_GYRO0_ZOFF:   0.000082234357250854

# 3.2. Accelerometer
CAL_ACC0_ID:      8388608
CAL_ACC0_PRIO:    50
CAL_ACC0_ROT:     0

# 3.3. Magnetometer
CAL_MAG0_ID:      8912896
CAL_MAG0_PRIO:    50
CAL_MAG0_ROT:     0

# 4. PID regulator
# ...
