release:
  org: PonomarevDA
  repo: PX4-Autopilot
  tag: v1.15.0-0.6.1-beta1
params:
  - configs/px4/v1.14/standard_vtol/airframe.yaml
  - configs/px4/v1.14/standard_vtol/dronecan.yaml
  - configs/px4/dronecan.yaml
  - configs/px4/common.yaml
mode: dronecan
alias: dv
sim_config: px4_v1_15_0_dronecan_quadplane_vtol
info: ""
