release:
  org: PonomarevDA
  repo: PX4-Autopilot
  tag: v1.15.0-0.6.1-beta1
params:
  - configs/px4/v1.15/standard_vtol/airframe.yaml
  - configs/px4/v1.15/standard_vtol/cyphal.yaml
  - configs/px4/cyphal.yaml
  - configs/px4/common.yaml
mode: cyphal
alias: csv
sim_config: px4_v1_15_0_cyphal_quadplane_vtol
info: ""
