release:
  org: PonomarevDA
  repo: PX4-Autopilot
  tag: v1.15.0-0.6.1-beta1
params:
  - configs/px4/v1.15/vtol_octoplane_coaxial/airframe.yaml
  - configs/px4/v1.15/vtol_octoplane_coaxial/cyphal.yaml
  - configs/px4/v1.15/vtol_octoplane_coaxial/geometry.yaml
  - configs/px4/cyphal.yaml
  - configs/px4/common.yaml
mode: cyphal
alias: cv8
sim_config: px4_v1_15_0_cyphal_octoplane_vtol
info: ""
