firmware: https://github.com/ZilantRobotics/PX4-Autopilot/releases/download/v1.15.0-0.4.2-alpha1/px4_fmu-v5_cyphal.px4
params:
  - configs/px4/v1.15/standard_vtol/airframe.yaml
  - configs/px4/v1.15/standard_vtol/cyphal.yaml
  - configs/px4/cyphal.yaml
  - configs/px4/common.yaml
mode: cyphal
alias: csv
sim_config: px4_v1_15_0_cyphal_quadplane_vtol
info: ""
