release:
  org: PonomarevDA
  repo: PX4-Autopilot
  tag: v1.15.0-0.6.1-beta1
params:
  - configs/px4/v1.14/quadcopter/airframe.yaml
  - configs/px4/v1.14/quadcopter/dronecan.yaml
  - configs/px4/dronecan.yaml
  - configs/px4/common.yaml
mode: dronecan
alias: dq
sim_config: px4_v1_15_0_dronecan_quadrotor
info: ""
