name: Catkin Build

on: [push]

defaults:
  run:
    shell: bash
jobs:
  catkin_build:
    if: false  # Disable it
    runs-on: ubuntu-20.04
    timeout-minutes: 8
    container:
      image: ros:noetic
    steps:
      - name: Handle issue with actions/checkout when Git version is less than 2.18 
        run: apt-get update && apt-get install -y git

      - uses: actions/checkout@v4
        with:
          path: catkin_ws/src/innopolis_vtol_dynamics
          submodules: recursive

      - name: Install requirements
        run: ./catkin_ws/src/innopolis_vtol_dynamics/scripts/install.sh --yes

      - name: catkin build
        run: source /opt/ros/noetic/setup.bash && cd catkin_ws && catkin build
