name: docker
on:
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - '*'
jobs:
  docker:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-13]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:

    - name: Set up Docker
      if: runner.os == 'Linux'
      uses: docker/setup-buildx-action@v2

    - name: Install Docker (macOS only)
      if: runner.os == 'macOS'
      run: |
        brew install docker colima
        colima start

    - name: Verify Docker
      run: |
        docker --version
        docker ps

    - name: Setup Python
      if: runner.os == 'macOS'
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Build project using Docker
      run: ./scripts/sim.py b
